# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push]

jobs:
  linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: building check
        run: echo test
      - name: unit tests
        run: echo unit_test
