name: Nodejs CI

<<<<<<< HEAD:.github/workflows/ci.yml
=======
name: check build frontend

# Controls when the action will run. 
>>>>>>> milestone2:.github/workflows/front.yml
on:
  push:
<<<<<<< HEAD:.github/workflows/ci.yml
    #branches: [ $default-branch ]
    branches: [ backend ]
  pull_request:
    branches: [ backend ]
=======
    branches: [ milestone2 ]
  pull_request:
    branches: [ milestone2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
>>>>>>> milestone2:.github/workflows/front.yml

jobs:
  build:

    runs-on: ubuntu-latest

<<<<<<< HEAD:.github/workflows/ci.yml
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run build-app
=======
      - name: build react
        run: cd application/frontend/app && npm install && CI= npm run build
>>>>>>> milestone2:.github/workflows/front.yml
